
name: Build, test

on:
    release:
        types: [created]
    push:
        branches:
            - main
            - dev

    workflow_dispatch:

permissions:
    contents: write

jobs:
    docker_amd64:
        runs-on: ubuntu-22.04

        steps:
            - name: Debug info
              run: |
                echo "event_name: ${{ github.event_name }}"
                echo "ref: ${{ github.ref }}"
                echo "ref_name: ${{ github.ref_name }}"
                echo "head_ref: ${{ github.head_ref }}"
                echo "base_ref: ${{ github.base_ref }}"

            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker build test
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  target: test
                  tags: msoma-test
                  load: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Run pytest docker
              uses: addnab/docker-run-action@v3
              with:
                  image: msoma-test
                  options: -v ${{ github.workspace }}:/msoma
                  run: pytest --docker --cov=src/ --cov-report=xml tests

            - name: Docker build prod
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: prod
                  tags: msoma_prod
                  load: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Nextflow setup
              uses: nf-core/setup-nextflow@v1

            - name: Nextflow test
              run: |
                cd examples
                nextflow run -with-docker msoma_prod --sampleSheet sample_sheet_chrM.tsv --outputDir nextflow_output mSOMA.nf
                cd ..

            - name: Login to DockerHub
              uses: docker/login-action@v3
              if: github.ref_name != 'main' && github.event_name != 'pull_request'
              with:
                  username: rbiermanpu
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Docker push
              uses: docker/build-push-action@v5
              if: github.ref_name != 'main' && github.event_name != 'pull_request'
              with:
                  context: .
                  target: prod
                  tags: rbiermanpu/msoma:${{ github.ref_name }}
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Docker build and push as "latest" if performing a release
              uses: docker/build-push-action@v5
              if: github.event_name == 'release'
              with:
                  context: .
                  tags: rbiermanpu/msoma
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64
                  push: true